---
title: "TidyTemplate"
date: 2022-11-22
output: html_document
---
```{r}
library(tidyverse)
library(showtext)

font_add_google("Rock Salt")
showtext_auto()

tt <- tidytuesdayR::tt_load("2022-11-22")

museums <- tt$museums %>% 
  separate(Subject_Matter, into = c("Subject_Cat", "Subject"), fill = "right", sep = "-", remove = FALSE, extra = "merge")

top_6 <- museums %>% 
  count(Subject_Cat,  sort =  TRUE) %>% 
  head(6) %>% 
  pull(Subject_Cat)
  

```

```{r fig.height=10, fig.width=4}
p <- museums %>%
  filter(Subject_Cat == "War_and_conflict") %>% 
  ggplot(aes(x = Longitude, y = Latitude))+
  geom_point(alpha = 0.8, aes(color = Accreditation), size = 2)+
  borders(database = "world")+
  annotate("text", x = 0, y = 60, label = "War & Conflict Museums", size = 12, family = "Rock Salt", hjust = "right", color = "#285430", fontface = "bold" )+
  annotate("text", x = 0, y = 59.5, label = "in the United Kingdom", size = 10, family = "Rock Salt", hjust = "right", color = "#285430")+
  scale_color_manual(values = c("#285430","#a38136"))+
  coord_quickmap(xlim = c(-8,3), ylim = c(49,60))+
  ggthemes::theme_map()+
  theme(text = element_text(family = "Rock Salt"),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 12),
        legend.background = element_rect(fill = "#faf9f0"),
        plot.background = element_rect(fill = "#faf9f0"))

ggsave(plot = p, filename = "uk_museums.png", device = "png")


```

